name: H3
channels:
  - conda-forge
dependencies:
  - geopandas=0.14.3
  - rasterio=1.3.8
  - rioxarray=0.14.1
  - rasterstats=0.17.0
  - shapely=2.0.1
  - pyproj=3.6.0
  - pandas=2.2.2
  - numpy=1.26.2
  - matplotlib=3.8.1
  - streamlit=1.27.0
  - tqdm=4.66.1
  - xarray=2024.6.0
  - fiona=1.9.4
  - scipy=1.11.3
  - ipykernel 
  - seaborn=0.13.2
  - unidecode=1.3.8
  - streamlit-folium